### ISSUE TITLE
PHP Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by TheOnlyDGS** [CodeMOOC/TreasureHuntBot#42]
Trying to install the bot on my server but when I run the **php pull.php** command, I get the following errors:

`PHP Fatal error: Uncaught Error: Class 'Message' was not found in ...src/model/context.php:107
Stack trace:
#0 ...src/model/context.php(49): Context->reload()
#1 ..src/msg_processing_cor.php(65): Context->_construct(Array)
#2 ..src/pull.php(48): include('')
#3 {main} thrown in ...src/model/context.php on line107
`
Can someone help me how to resolve these errors?

Thanks in advance.

**Comment by LorenzCK** [comment]
Hello @TheOnlyDGS, sorry about the late reply. Were you able to fix the error? This looks like PHP is unable to load the Message class (in the `message.php` file). Are there other warnings or errors above? Which version of PHP are you using?

**Comment by TheOnlyDGS** [comment]
The php version is 7.4.30, not able to fix the error so stuck deploying it on my server.

The error screenshot is https://snipboard.io/VyuIcT.jpg
